name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # use your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # - name: Build APK
      #   run: flutter build apk --release

      # If you want to upload APK as artifact
      # - name: Upload APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release
      #     path: build/app/outputs/flutter-apk/app-release.apk

      - name: Decode Service Account
        run: echo "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" > play-account.json

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Publish to Play Store
        working-directory: android
        run: ./gradlew publishReleaseBundle

      # 🔥 Firebase App Distribution step
      # - name: Upload to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     # token: ${{ secrets.FIREBASE_TOKEN }}
      #     serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #     file: build/app/outputs/flutter-apk/app-release.apk
      #     testers: "nellaidinesh5@gmail.com,dinunellai@gmail.com"
